name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and deploy to Minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
      - name: Try the Cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "Verifying images:"
          docker images         
      - name: Deploy to Minikube
        run: kubectl apply -f k8s-node-app.yaml
      - name: Check Pods Status
        run: kubectl get pods -n default
      - name: Get Logs from Pod
        run: |
          POD_NAME=$(kubectl get pods -l app=nodejs-app -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME
      - name: Get Deployment Events
        run: kubectl describe deployment nodejs-app
      - name: Test Service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url

